name: Code Quality (Laravel Pint)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test
